import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  flatListContent: {
    paddingBottom: 100,
  },
  gallerySection: {
    height: 260,
    position: 'relative',
  },
  galleryImage: {
    width: '100%',
    height: '100%',
  },
  galleryOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  backBtnLight: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  iconBtnLight: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  galleryIndicator: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  galleryIndicatorText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  contentSection: {
    padding: 16,
    marginVertical: 20,
  },
  courtDetailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  courtDetailInfo: {
    flex: 1,
  },
  premiumBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#00D9B5',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    marginBottom: 8,
  },
  premiumBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#fff',
  },
  detailTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#000',
    marginBottom: 8,
  },
  courtRatingLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingScore: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000',
  },
  ratingCount: {
    fontSize: 14,
    color: '#666',
  },
  courtStatusLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4CAF50',
  },
  statusText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4CAF50',
  },
  quickInfoGrid: {
    gap: 12,
  },
  quickInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#f9f9f9',
    padding: 12,
    borderRadius: 12,
  },
  quickInfoText: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 12,
    color: '#999',
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
  },
  priceBookingCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#f9f9f9',
    padding: 16,
    borderRadius: 12,
  },
  priceSection: {
    flex: 1,
  },
  priceLabel: {
    fontSize: 12,
    color: '#999',
    marginBottom: 4,
  },
  priceRange: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
    marginBottom: 4,
  },
  priceFrom: {
    fontSize: 18,
    fontWeight: '700',
    color: '#00D9B5',
  },
  priceSeparator: {
    fontSize: 14,
    color: '#999',
  },
  priceTo: {
    fontSize: 18,
    fontWeight: '700',
    color: '#00D9B5',
  },
  priceUnit: {
    fontSize: 12,
    color: '#999',
  },
  priceNote: {
    fontSize: 11,
    color: '#999',
  },
  bookBtn: {
    backgroundColor: '#00D9B5',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  bookBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  sectionHeading: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000',
    marginBottom: 12,
  },
  descriptionText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    marginBottom: 12,
  },
  facilitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  facilityItem: {
    width: width * 0.5 - 24,
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f9f9f9',
    paddingVertical: 16,
    borderRadius: 12,
  },
  facilityIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E0F7F4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  facilityName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
  },
  mapContainer: {
    height: 200,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 12,
    position: 'relative',
  },
  mapImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapActionBtn: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#00D9B5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  mapActionBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  locationDetail: {
    gap: 8,
  },
  locationAddress: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
  },
  locationDistance: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  locationDistanceText: {
    fontSize: 13,
    color: '#666',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  reviewBtnSmall: {
    borderWidth: 1,
    borderColor: '#00D9B5',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  reviewBtnSmallText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#00D9B5',
  },
  ratingSummary: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 20,
    padding: 16,
    borderRadius: 12,
  },
  ratingOverview: {
    alignItems: 'center',
    gap: 8,
  },
  ratingBig: {
    fontSize: 36,
    fontWeight: '700',
    color: '#000',
  },
  ratingStars: {
    flexDirection: 'row',
    gap: 2,
  },
  ratingCountText: {
    fontSize: 12,
    color: '#999',
  },
  ratingBars: {
    flex: 1,
    gap: 8,
  },
  ratingBarItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  barLabel: {
    fontSize: 12,
    color: '#999',
    width: 30,
  },
  barTrack: {
    flex: 1,
    height: 6,
    backgroundColor: '#f0f0f0',
    borderRadius: 3,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    backgroundColor: '#00D9B5',
  },
  barCount: {
    fontSize: 12,
    color: '#999',
    width: 30,
    textAlign: 'right',
  },
  reviewsList: {
    gap: 12,
  },
  reviewItem: {
    backgroundColor: '#f9f9f9',
    padding: 12,
    borderRadius: 12,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  reviewAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reviewAvatarText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  reviewUserInfo: {
    flex: 1,
  },
  reviewUserName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#000',
    marginBottom: 2,
  },
  reviewRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  reviewRatingText: {
    fontSize: 12,
    color: '#FFB800',
    fontWeight: '600',
  },
  reviewDate: {
    fontSize: 12,
    color: '#999',
  },
  reviewText: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },
  viewAllBtn: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#00D9B5',
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 12,
  },
  viewAllBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#00D9B5',
  },
  detailFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  footerInfo: {
    gap: 4,
  },
  footerPriceLabel: {
    fontSize: 12,
    color: '#999',
  },
  footerPriceValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#00D9B5',
  },
  footerBtn: {
    backgroundColor: '#00D9B5',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  footerBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
});
