import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerContainer: {
    position: 'relative',
    height: 220,
    marginBottom: 16,
  },
  headerImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerGradient: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#00D9B5',
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: 'white',
  },
  headerSubtitle: {
    fontSize: 20,
    color: 'white',
    marginTop: 8,
  },
  backBtn: {
    position: 'absolute',
    top: 16,
    left: 16,
    width: 40,
    height: 40,
    justifyContent: 'center',
  },
  headerActions: {
    position: 'absolute',
    top: 16,
    right: 16,
    flexDirection: 'row',
    gap: 12,
  },
  iconBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contentSection: {
    padding: 16,
    marginBottom: 24,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00D9B5',
  },
  statusText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#999',
  },
  infoCardsGrid: {
    paddingHorizontal: 16,
  },
  infoCard: {
    borderRadius: 12,
    alignItems: 'center',
    padding: 12,
    flex: 1,
    justifyContent: 'center',
  },
  infoLabel: {
    fontSize: 12,
    color: '#999',
    marginTop: 8,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    marginTop: 4,
    textAlign: 'center',
  },
  tabsContainer: {
    paddingHorizontal: 16,
    marginBottom: 24,
    flexDirection: 'row',
    gap: 8,
  },
  tabBtn: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabBtnActive: {
    borderBottomColor: '#00D9B5',
  },
  tabLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#999',
  },
  tabLabelActive: {
    color: '#00D9B5',
  },
  sectionHeading: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 14,
  },
  descriptionText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 22,
    marginBottom: 12,
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  categoryCard: {
    width: '32%',
    alignItems: 'center',
    marginBottom: 16,
    padding: 12,
    borderRadius: 12,
  },
  categoryIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#00D9B5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  categoryName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
  },
  categoryCount: {
    fontSize: 11,
    color: '#999',
  },
  feeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    marginBottom: 10,
  },
  feeItemFeatured: {
    backgroundColor: '#f0f9f8',
    borderLeftWidth: 3,
    borderLeftColor: '#00D9B5',
  },
  feeName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#000',
  },
  feeRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  feeAmount: {
    fontSize: 14,
    fontWeight: '600',
    color: '#00D9B5',
  },
  feeBadge: {
    backgroundColor: '#FF6B6B',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  feeBadgeText: {
    fontSize: 11,
    color: 'white',
    fontWeight: '600',
  },
  organizerCard: {
    flexDirection: 'row',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    backgroundColor: '#f8f8f8',
    borderRadius: 12,
  },
  organizerLogo: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#00D9B5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  organizerLogoText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'white',
  },
  organizerInfo: {
    flex: 1,
  },
  organizerName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
  },
  organizerDesc: {
    fontSize: 12,
    color: '#999',
    marginBottom: 8,
  },
  contactLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  contactText: {
    fontSize: 12,
    color: '#00D9B5',
    fontWeight: '500',
  },
  footer: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    backgroundColor: '#fff',
  },
  footerInfo: {
    marginBottom: 12,
  },
  priceLabel: {
    fontSize: 12,
    color: '#999',
    marginBottom: 4,
  },
  priceValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#00D9B5',
  },
  deadlineInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
  },
  deadlineText: {
    fontSize: 12,
    color: '#666',
  },
  registerBtn: {
    backgroundColor: '#00D9B5',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
  },
  registerBtnText: {
    fontSize: 16,
    fontWeight: '600',
    color: 'white',
  },
});
