import { Ranking } from '../types';

export const rankings: Ranking[] = [
  {
    rank: 1,
    name: 'Alpha',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Alpha',
    elo: 2450,
    tier: 'Legend',
    winRate: 72.4,
  },
  {
    rank: 2,
    name: 'Bravo',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Bravo',
    elo: 2390,
    tier: 'Master',
    winRate: 70.1,
  },
  {
    rank: 3,
    name: 'Charlie',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Charlie',
    elo: 2310,
    tier: 'Master',
    winRate: 68.3,
  },
  {
    rank: 4,
    name: 'Delta',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Delta',
    elo: 2260,
    tier: 'Diamond',
    winRate: 65.8,
  },
  {
    rank: 5,
    name: 'Echo',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Echo',
    elo: 2210,
    tier: 'Diamond',
    winRate: 64.2,
  },
  {
    rank: 6,
    name: 'Foxtrot',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Foxtrot',
    elo: 2170,
    tier: 'Platinum',
    winRate: 63.5,
  },
  {
    rank: 7,
    name: 'Golf',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Golf',
    elo: 2130,
    tier: 'Platinum',
    winRate: 62.8,
  },
  {
    rank: 8,
    name: 'Hotel',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Hotel',
    elo: 2090,
    tier: 'Gold',
    winRate: 61.3,
  },
  {
    rank: 9,
    name: 'India',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=India',
    elo: 2050,
    tier: 'Gold',
    winRate: 59.9,
  },
  {
    rank: 10,
    name: 'Juliet',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Juliet',
    elo: 2010,
    tier: 'Gold',
    winRate: 58.7,
  },
  {
    rank: 11,
    name: 'Kilo',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Kilo',
    elo: 1970,
    tier: 'Silver',
    winRate: 57.2,
  },
  {
    rank: 12,
    name: 'Lima',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Lima',
    elo: 1930,
    tier: 'Silver',
    winRate: 55.4,
  },
  {
    rank: 13,
    name: 'Mike',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Mike',
    elo: 1890,
    tier: 'Silver',
    winRate: 54.1,
  },
  {
    rank: 14,
    name: 'November',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=November',
    elo: 1850,
    tier: 'Bronze',
    winRate: 52.8,
  },
  {
    rank: 15,
    name: 'Oscar',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Oscar',
    elo: 1810,
    tier: 'Bronze',
    winRate: 51.3,
  },
  {
    rank: 16,
    name: 'Papa',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Papa',
    elo: 1770,
    tier: 'Bronze',
    winRate: 50.9,
  },
  {
    rank: 17,
    name: 'Quebec',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Quebec',
    elo: 1730,
    tier: 'Iron',
    winRate: 49.5,
  },
  {
    rank: 18,
    name: 'Romeo',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Romeo',
    elo: 1690,
    tier: 'Iron',
    winRate: 48.2,
  },
  {
    rank: 19,
    name: 'Sierra',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Sierra',
    elo: 1650,
    tier: 'Iron',
    winRate: 47.0,
  },
  {
    rank: 20,
    name: 'Tango',
    avatar: 'http://api.dicebear.com/9.x/lorelei/svg?seed=Tango',
    elo: 1610,
    tier: 'Iron',
    winRate: 45.6,
  },
];
